### ISSUE TITLE
Config design and implementation

### ISSUE THREAD

**Issue by hadronomy** [Hadronomy/psmt-rs#1]
### Description

Design the layout and rules to take into account when adding configuration options to `psmt.toml`.
Implement a good API for using the configuration throughout the whole project.

### Design

The `psmt.toml` file will contain the template configuration as a subkey.
This way the template variables can be defined as an array of maps inside of `template`.

Template configuration will look something like this:
```toml
[template]
name = "example"
version = "0.1.0"
license = "MIT"

[[template.variables]]
name = "Example"
question = "This is an example question"

```

Note that the **name**, **version** and **license** are defined inside the template configuration.
These fields are only required because by defining the template configuration, it's assumed that it's a template project.

If insufficient the type of the project could be defined in the following format:

```toml
type = "template"

```

### Implementation

`libpsmt` will contain a `config` module, where the logic and API for managing the configuration will reside.
The configuration is defined as a struct `TemplateConfig`, alongside all the required structs.

The config API must be flexible while ensuring correctness.
